
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt
    username: root
    password: yeram0910
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
